# Generated by Django 5.0.6 on 2024-06-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('css_selector', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'ScrapperConfig',
                'verbose_name_plural': 'ScrapperConfigs',
            },
        ),
    ]
